# Build documentation and upload to gh-pages
name: Ensure documentation builds after commits

defaults:
  run:
    shell: bash

on: [push, pull_request]  # Runs on all push events to any branch

jobs:
  documentation:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build documentation
        run: python -m mkdocs build -d ./doc_build

      # Upload artifacts if in PR so reviewers can have a quick look without building documentation from the branch locally
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success() && github.event_name == 'pull_request'
        with:
          name: site-build
          path: doc_build
          retention-days: 5
